name: 'Microsoft Teams Notification'
description: 'Send a custom notification message to a Microsoft Teams channel with GitHub repo details'

branding:
  icon: message-circle
  color: purple

inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  ms-teams-webhook-uri:
    description: 'Microsoft Teams Webhook URI'
    required: true
  notification-summary:
    description: 'Message to be sent to Microsoft Teams channel'
    required: true
  notification-color:
    description: 'Color of notification header line'
    required: true
  timezone:
    description: 'Timezone (ex. America/Denver)'
    required: false
  github-repository:
    description: 'GitHub Repository'
    required: true
  github-sha:
    description: 'GitHub SHA'
    required: true

runs:
  using: 'node12'
  main: 'index.js'